version: "3.5"

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args: &app-args
        PROJECT_NAME: ${PROJECT_NAME}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}

    command: /entrypoints/start-django.sh

    environment: &app-environment
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_DJANGO_DIR: ${PROJECT_DJANGO_DIR}
      LOGGING_ROOT_DIR: /logs
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      REDIS_HOST: ${REDIS_HOST:-redis}
      EMAIL_SENDER_TYPE: ${EMAIL_SENDER_TYPE}
    ports:
      - "8000"
      - "${DJANGO_DEBUG_PORT}:8000"
    volumes:
      - vol_logs:/logs
      - vol_static:/static
    depends_on:
      - postgres
      - redis
    links:
      - postgres

  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - vol_postgres:/var/lib/postgresql/data
      - vol_logs:/logs
      - ./data/psql_dump.sql:/docker-entrypoint-initdb.d/psql_dump.sql
    shm_size: "128mb"

  redis:
    image: redis:7.0.4-alpine

  celery_worker:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        <<: *app-args
    command: /entrypoints/start-celery-worker.sh
    environment:
      <<: *app-environment
    volumes:
      - vol_logs:/logs
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        <<: *app-args
    command: /entrypoints/start-flower.sh
    environment:
      <<: *app-environment
    ports:
      - 5557:5555
    depends_on:
      - celery_worker
      - app

volumes:
  vol_postgres:
    driver: local
  vol_logs:
    driver: local
  vol_static:
    driver: local